using System;
using System.Collections.Generic;
using GameSaveCenter.Contracts;

namespace GameSaveCenter.Core.Models
{
    /// <summary>Internal game identity and matching information.</summary>
    public sealed class GameProfile
    {
        public string PlayniteId { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public GamePlatformKind Platform { get; set; }
        public string PlatformGameId { get; set; } = string.Empty;
        public string InstallDirectory { get; set; } = string.Empty;
        public string LudusaviName { get; set; } = string.Empty;
        public List<string> ProcessNames { get; set; } = new List<string>();
        public BackupPolicy Policy { get; set; } = new BackupPolicy();
    }

    /// <summary>Domain backup policy with conservative restore defaults.</summary>
    public sealed class BackupPolicy
    {
        public bool Enabled { get; set; } = true;
        public bool BackupOnGameStop { get; set; } = true;
        public bool BackupDuringPlay { get; set; } = true;
        public TimeSpan DuringPlayInterval { get; set; } = TimeSpan.FromMinutes(30);
        public bool UploadAfterBackup { get; set; }
        public bool SyncMediaDuringPlay { get; set; } = true;
        public bool SyncMediaOnGameStop { get; set; } = true;
        public bool AllowAutomaticRestore { get; set; }
        public RetentionPolicy Retention { get; set; } = new RetentionPolicy();
    }

    /// <summary>Time-bucket retention settings.</summary>
    public sealed class RetentionPolicy
    {
        public TimeSpan KeepAllFor { get; set; } = TimeSpan.FromHours(24);
        public int KeepDailyDays { get; set; } = 30;
        public int KeepWeeklyWeeks { get; set; } = 12;
        public int KeepMonthlyMonths { get; set; } = 24;
    }

    /// <summary>File metadata captured without storing file contents.</summary>
    public sealed class FileManifestEntry
    {
        public string RelativePath { get; set; } = string.Empty;
        public long SizeBytes { get; set; }
        public DateTime LastWriteUtc { get; set; }
        public string Sha256 { get; set; } = string.Empty;
        public bool IsRegistryValue { get; set; }
    }

    /// <summary>Comparable backup summary used by validation and retention.</summary>
    public sealed class BackupSnapshot
    {
        public string BackupId { get; set; } = string.Empty;
        public string ParentBackupId { get; set; } = string.Empty;
        public DateTime CreatedUtc { get; set; }
        public long TotalBytes { get; set; }
        public int FileCount { get; set; }
        public bool IsLocked { get; set; }
        public bool IsPreRestore { get; set; }
        public string Comment { get; set; } = string.Empty;
        public string SourceDevice { get; set; } = string.Empty;
        public RestoreReadinessStatus? ReadinessStatus { get; set; }
        public bool HasSevereAnomaly { get; set; }
        public bool IsHealthyRestorePoint => !HasSevereAnomaly && ReadinessStatus == RestoreReadinessStatus.Ready;
        public List<FileManifestEntry> Files { get; set; } = new List<FileManifestEntry>();
    }

    /// <summary>Candidate save location discovered by before/after comparison.</summary>
    public sealed class SavePathCandidate
    {
        public string Path { get; set; } = string.Empty;
        public double Score { get; set; }
        public int ChangedFileCount { get; set; }
        public int SaveLikeExtensionCount { get; set; }
        public int CacheLikeExtensionCount { get; set; }
        public bool ChangedNearSessionEnd { get; set; }
        public bool RepeatedAcrossSessions { get; set; }
        public bool LocatedInXboxWgs { get; set; }
        public List<string> Reasons { get; set; } = new List<string>();
    }

    /// <summary>Potential divergent state between two devices.</summary>
    public sealed class DeviceConflict
    {
        public bool HasConflict { get; set; }
        public string Reason { get; set; } = string.Empty;
        public string PreferredBackupId { get; set; } = string.Empty;
        public double Confidence { get; set; }
    }

    /// <summary>Validation finding generated by pure domain rules.</summary>
    public sealed class ValidationFinding
    {
        public FindingSeverity Severity { get; set; }
        public string Code { get; set; } = string.Empty;
        public string Title { get; set; } = string.Empty;
        public string Detail { get; set; } = string.Empty;
        public string SuggestedAction { get; set; } = string.Empty;
    }

    /// <summary>Difference between two file manifests.</summary>
    public sealed class FileManifestDiff
    {
        public List<FileManifestEntry> Added { get; set; } = new List<FileManifestEntry>();
        public List<FileManifestEntry> Removed { get; set; } = new List<FileManifestEntry>();
        public List<FileManifestEntry> Modified { get; set; } = new List<FileManifestEntry>();
        public List<FileManifestEntry> Unchanged { get; set; } = new List<FileManifestEntry>();
        public bool IsExactComparison { get; set; }
        public long BeforeTotalBytes { get; set; }
        public long AfterTotalBytes { get; set; }
    }
}
